-- ATIVIDADE --
CREATE DATABASE ESCOLA_AMIL;
CREATE DATABASE IF NOT EXISTS ESCOLA_AMIL
USE ESCOLA_AMIL
DROP DATABASE DATABASE ESCOLA_AMIL;
-- CRIAR TABELA
CREATE TABLE PROFESSORES (
ID_PROFESSORES INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR (60) NOT NULL,
FORMACAO VARCHAR (30) NOT NULL, 
SERIES VARCHAR(15) DEFAULT "ENSINO FUNDAMENTAL",
MATERIA VARCHAR (30) NOT NULL,
QAUNTIDADE_AULAS VARCHAR (50) NOT NULL
);

