-- PROJETO SMARTCOFFEE

CREATE DATABASE SMARTCOFFEE_GABRIELA;

USE SMARTCOFFEE_GABRIELA;

CREATE TABLE PEDIDOS (
ID_PEDIDOS INT AUTO_INCREMENT PRIMARY KEY,
PRODUTO CHAR (50) DEFAULT "TIPO",
ENDERECO VARCHAR (60) NOT NULL,
ENTEGADOR VARCHAR (45) NOT NULL,
CLIENTE  VARCHAR (60) NOT NULL, 
FORMA_PAGAMENTO ENUM ("DÉBITO", "CRÉDITO", "PIX", "DINHEIRO") 
);

CREATE TABLE PRODUTO (
ID_PRODUTO INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR (60) NOT NULL, 
CATEGORIA CHAR (60) DEFAULT "TIPO",
VALIDADE DATETIME (50) NOT FULL,
PRECO DECIMAL ("5,5"), 0.00,
QUANTIDADE VARCHAR (60) NOT NULL
);

CREATE TABLE PAGAMENTOS 







CREATE TABLE ESTOQUE (
ID_ESTOQUE INT AUTO_INCREMENT PRIMARY KEY,
QUANTIDADE 
