-- 1
-- COMANDOS PARA CRIAR BD

CREATE DATABASE ESCOLA_GABRIELA;

-- 2
-- ATUALIZAR SCHEMAS

-- COMANDO PARA APAGAR BD
-- 3 
USE ESCOLA_GABRIELA
DROP DATABASE ESCOLA_GABRIELA;
-- COMANDO PARA APAGAR TABELA
DROP TABLE ALUNOS;

-- COMANDO CRIAR TABELA
CREATE TABLE ALUNOS (
ID_ALUNOS INT AUTO_INCREMENT PRIMARY KEY,
SERIE VARCHAR (14) NOT NULL UNIQUE,
NOME VARCHAR (60) NOT NULL,
TURNO VARCHAR (10) DEFAULT "INTEGRAL",
DATA_DE_NASCIMENTO DATE NOT NULL,
RA VARCHAR (11),
STATUS_ALUNOS ENUM ('PENDENTE', 'ATIVO', 'INATICO' ) DEFAULT "ATIVO"
DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- COMANDOS PARA ALTERAR E CORRIGIR
-- ADICIONANDO UM CAMPO (ATRIBUTO) NOVO
ALTER TABLE CLIENTES ADD EMAIL VARCHAR(100);

-- VISUALIZAR TABELAS NO BD
SHOW TABLES;

-- MODIFICAR TIPO DE DADOS OU CAMPOS 
ALTER TABLE ALUNOS ADD EMAIL VARCHAR(150);

-- RENOMEAR TABELAS 
RENAME TABLE ALUNOS TO ALUNOS;

-- VISUALIZAR TABELAS NO BD
SHOW TABLES 




CREATE DATABASE ESCOLA_AMIL;
USE ESCOLA_AMIL
DROP DATABASE DATABASE ESCOLA_AMIL;
-- CRIAR TABELA
CREATE TABLE PROFESSORES (
ID_PROFESSORES INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR (60) NOT NULL,
FORMACAO VARCHAR (30) NOT NULL, 
SERIES VARCHAR(15) DEFAULT "ENSINO FUNDAMENTAL",
MATERIA VARCHAR (30) NOT NULL,
QAUNTIDADE_AULAS VARCHAR (50) NOT NULL,
);
 



