CREATE DATABASE OFICINA_GABRIELA;
USE OFICINA_GABRIELA;
CREATE TABLE IF NOT EXISTS CLIENTES (
    ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
    NOME_CLIENTE VARCHAR(60) NOT NULL,
    ENDERECO VARCHAR(100) NOT NULL, 
    CPF_CLIENTE CHAR(14) NOT NULL UNIQUE, 
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTIS VEICULOS (
    ID_VEICULOS INT AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO_PROBLEMA TEXT(300) NOT NULL,
    PLACA CHAR(8) NOT NULL UNIQUE,
    COR VARCHAR(25) NOT NULL,
    MARCA VARCHAR(25) NOT NULL,
    QUILOMETRAGEM INT
);

CREATE TABLE IF NOT EXISTS MARCAS (
    ID_MARCA INT AUTO_INCREMENT PRIMARY KEY,
    NOME_MARCA VARCHAR(50) NOT NULL, 
    PAIS_ORIGEM VARCHAR(30),
    ANO_LANCAMENTO YEAR,
    MODELO TEXT(500),
    TIPO_COMBUSTIVEL ENUM ('GASOLINA', 'ETANOL','DIESEL')
    DEFAULT 'ETANOL' NOT NULL,
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIME
);

CREATE TABLE MODELOS (
    ID_MODELOS INT AUTO_INCREMENT PRIMARY KEY,
    NOME_MODELO VARCHAR(30) NOT NULL,
    TIPO_DE_MODELO ENUM('SUV','COMPACTO', 'SEDAN') DEFAULT 'COMPACTO',
    ANO_FABRICACAO YEAR NOT NULL,
    POTENCIA CHAR,
    STATUS_MODELO ENUM ('ATIVO', 'INATIVO') DEFAULT 'ATIVO',
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS FUNCIONARIOS (
    ID_FUNCIONARIOS INT AUTO_INCREMENT PRIMARY KEY,
    NOME_FUNCIONARIO VARCHAR(60) NOT NULL,
    CPF_FUNCIONARIO CHAR(14) NOT NULL UNIQUE,
    TELEFONE_FUNCIONNARIO CHAR(15) NOT NULL,
    CARGO VARCHAR(30),
    SALARIO DECIMAL (10,2) NOT NULL,
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS SERVICOS (
    ID_SERVICOS INT AUTO_INCREMENT PRIMARY KEY,
    TIPO_SERVICOS VARCHAR(100) NOT NULL,
    VALOR DECIMAL(10,2) NOT NULL,
    DATA_INICIO DATETIME NOT NULL,
    DATA_TERMINO DATETIME NOT NULL,
    DESCRICAO_SERVICO TEXT(500) NOT NULL,
    STATUS_SERVICOS ENUM ('EM ANDAMENTO', 'EM ESPERA', 'CONCLUÍDO') DEFAULT 'EM ANDAMENTO', NOT NULL,
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS FORNECEDORES (
    ID_FORNECEDORES INT AUTO_INCREMENT PRIMARY KEY,
    TELEFONE CHAR(15) NOT NULL,
    --TEMPO_ENTREGA VARCHAR(30)
    CNPJ CHAR(18) NOT NULL UNIQUE,
    RAZAO_SOCIAL VARCHAR(100) NOT NULL,
    SEGMENTO_AREA VARCHAR(50) NOT NULL,
    ENDERECO VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    STATUS_FORNECEDOR ENUM ('ATIVO', 'INATIVO') DEFAULT 'ATIVO'
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);